name: Go

on:
  push:
    branches:
      - master
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    outputs:
      new_release_major_version: ${{ steps.semantic.outputs.new_release_major_version }}
      new_release_minor_version: ${{ steps.semantic.outputs.new_release_minor_version }}
      new_release_patch_version: ${{ steps.semantic.outputs.new_release_patch_version }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: go build -v ./...
      - run: go test -v ./...

      - name: Semantic Release
        if: ${{ github.ref == '/refs/heads/master' }}
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 16
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker_release:
    runs-on: ubuntu-latest

    if: ${{ github.ref == '/refs/heads/master' }}

    needs:
      - build_and_release

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,enable=true,prefix=v,value=${{ needs.build_and_release.new_release_version }}
            type=raw,enable=true,prefix=v,value=${{ needs.build_and_release.new_release_major_version }}
            type=raw,enable=true,prefix=v,value=${{ needs.build_and_release.new_release_major_version }}.${{ steps.semantic.outputs.new_release_major_version }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
